const obj = [
  {
    createdAt: "27.4.2022",
    id: "TULQtWF8",
    info: { txt: "Just plain text..." },
    isPinned: false,
    style: { backgroundColor: "brown" },
    type: "note-txt",
  },
  {
    createdAt: "29.4.2022",
    id: "kMGxJG5k",
    info: { txt: "Must remember to deep refresh..." },
    isPinned: true,
    style: { backgroundColor: "rgb(197, 79, 197)" },
    type: "note-txt",
  },
  {
    createdAt: "27.4.2022",
    id: "fq7LtKgB",
    info: { mapHeading: "My map", locations: [], mapId: "sUGuFyE1" },
    isPinned: false,
    style: { backgroundColor: "rgb(197, 79, 197)" },
    type: "note-map",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "vzKWmPdf",
    info: {
      imgUrl:
        "https://media1.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif?cid=ecf05e47c523bdd44358f15c430b4036d5c18c1866c50029&rid=giphy.gif&ct=g",
    },
    isPinned: true,
    desc: "me realizing i can just copy code from the internet and nobody will know",
    style: { backgroundColor: "brown" },
    type: "note-img",
  },
  {
    createdAt: "27.4.2022",
    id: "VUaNwVfk",
    info: { videoUrl: "https://www.youtube.com/watch?v=FWy_LbhHtug" },
    isPinned: true,
    style: { backgroundColor: "rgb(98, 167, 98)" },
    type: "note-video",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "5LYmTwGE",
    info: { videoUrl: "https://www.youtube.com/watch?v=6OkUjnrfjC4" },
    isPinned: false,
    style: { backgroundColor: "dodgerblue" },
    type: "note-video",
    desc: "Place for some text..",
  },
  {
    createdAt: "23.01.1997",
    id: "Bs9Ki8eK",
    info: { txt: "Avi was born today!!!" },
    isPinned: false,
    style: { backgroundColor: "brown" },
    type: "note-txt",
  },
  {
    createdAt: "27.4.2022",
    id: "WibOV3eE",
    info: { imgUrl: "https://www.coding-academy.org/images/team/yaron.jpg" },
    isPinned: false,
    style: { backgroundColor: "yellow" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "MCkDU6MA",
    info: {
      imgUrl: "https://c.tenor.com/yY_2I-E9xNIAAAAC/head-banging-anime.gif",
    },
    isPinned: false,
    style: { backgroundColor: "yellow" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "4nwDIIhL",
    info: { imgUrl: "https://giphy.com/gifs/papermag-e5EcjjJx3dCFi" },
    isPinned: false,
    style: { backgroundColor: "yellow" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "8XSlk1Lw",
    info: {
      imgUrl:
        "https://media1.giphy.com/media/e5EcjjJx3dCFi/giphy.gif?cid=ecf05e47haac99zn8nei22fhddyeu2kg4rftx4ezczunv3ql&rid=giphy.gif&ct=g",
    },
    isPinned: false,
    style: { backgroundColor: "brown" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "pq6tTpYj",
    info: { imgUrl: "https://giphy.com/gifs/forever-alone-V46sLZRVrOUXm" },
    isPinned: true,
    style: { backgroundColor: "tomato" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "4Bg3PiI1",
    info: { videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
    style: { backgroundColor: "brown" },
    isPinned: true,
    type: "note-video",
    desc: "Place for some text..",
  },
  {
    createdAt: "30.4.2022",
    id: "BKjSiFB8",
    info: { videoUrl: "https://www.youtube.com/watch?v=EPIlAiOTqLY" },
    style: { backgroundColor: "yellow" },
    isPinned: false,
    type: "note-video",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "LWpWPaXD",
    info: { txt: "one more note" },
    style: { backgroundColor: "rgb(98, 167, 98)" },
    isPinned: false,
    type: "note-txt",
  },
  {
    createdAt: "27.4.2022",
    id: "oAepEIkA",
    info: { txt: "my note" },
    style: { backgroundColor: "rgb(197, 79, 197)" },
    isPinned: true,
    type: "note-txt",
  },
  {
    createdAt: "27.4.2022",
    id: "InN3D8f0",
    info: {
      imgUrl: "https://c.tenor.com/NOGjHRHDL_cAAAAC/naruto-uzumaki-naruto.gif",
    },
    style: { backgroundColor: "rgb(98, 167, 98)" },
    isPinned: false,
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "SKYMkt0f",
    info: {
      imgUrl:
        "https://images.unsplash.com/photo-1651020696818-9b44bcc38f40?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    },
    isPinned: false,
    style: { backgroundColor: "dodgerblue" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "27.4.2022",
    id: "f4VEyKbC",
    info: {
      imgUrl:
        "https://images.unsplash.com/photo-1650997062224-e1d14f5143ed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80",
    },
    isPinned: true,
    style: { backgroundColor: "brown" },
    type: "note-img",
    desc: "Place for some text..",
  },
  {
    createdAt: "30.4.2022",
    id: "nZUnIP5Q",
    info: {
      imgUrl:
        "https://c.tenor.com/VU4nI9l0e64AAAAC/majin-boo-dragon-ball-z.gif",
    },
    isPinned: true,
    style: { backgroundColor: "rgb(197, 79, 197)" },
    desc: "Me after a whole day of sprint and no eating",
    type: "note-img",
  },
  {
    createdAt: "27.4.2022",
    id: "dR77mnDv",
    info: { canvasHeading: "my canvas" },
    isPinned: false,
    style: { backgroundColor: "tomato" },
    type: "note-canvas",
    desc: "Place for some text..",
  },
  {
    createdAt: "30.4.2022",
    id: "FilLUU5u",
    info: {
      todoHeading: "Doing sprint 3",
      todos: [
        { txt: "open vscode", isDone: false, id: "dgQmxBKE" },
        { txt: "FREAK OUT!!!", isDone: true, id: "yi77V3gY" },
        { txt: "Submit project...", isDone: false, id: "uwzaW2BJ" },
      ],
    },
    isPinned: true,
    type: "note-todo",
    desc: "Place for some text..",
  },
  {
    createdAt: "30.4.2022",
    id: "FilLMU5u",
    info: {
      todoHeading: "Doing sprint 4",
      todos: [
        { txt: "FREAK OUT!!!", isDone: false, id: "yi77V3gY" },
        { txt: "FREAK OUT!!!", isDone: false, id: "yi77q3gY" },
        { txt: "FREAK OUT!!!", isDone: false, id: "yi77f3gY" },
        { txt: "FREAK OUT!!!", isDone: false, id: "yi77s3gY" },
        { txt: "FREAK OUT!!!", isDone: false, id: "yi7793gY" },
      ],
    },
    isPinned: false,
    type: "note-todo",
    desc: "Place for some text..",
  },
  {
    createdAt: "30.4.2022",
    id: "FilHMU5u",
    info: {
      todoHeading: "Things todo after sprint",
      todos: [
        { txt: "Eat", isDone: false, id: "yi77V3gY" },
        { txt: "Shower", isDone: false, id: "yi77q3gY" },
        { txt: "Eat", isDone: false, id: "yi77f3gY" },
        { txt: "Feed cat", isDone: false, id: "yi77s3gY" },
        { txt: "Keep working on sprint :(...", isDone: false, id: "yi7793gY" },
      ],
    },
    isPinned: false,
    type: "note-todo",
    desc: "Place for some text..",
  },
  {
    id: "Zq8SZVoU",
    type: "note-email",
    isPinned: false,
    createdAt: "30.4.2022",
    desc: "Place for some text...",
    info: {
      to: "user@appsus.com",
      subject: "SpaceX",
      body: "Would you like to join?",
    },
  },
  {
    id: "0U7jZ8EC",
    type: "note-email",
    isPinned: false,
    createdAt: "30.4.2022",
    info: {
      to: "user@appsus.com",
      subject: "SpaceX",
      body: "Would you like to join?",
    },
  },
  {
    id: "WtJW6Ri8",
    type: "note-email",
    isPinned: false,
    createdAt: "30.4.2022",
    info: {
      to: "user@appsus.com",
      subject: "Pulse Hex progress",
      body: "Dont worry, prec-20 will be ready soon!",
    },
  },
];
